service: ex6

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - "arn:aws:lambda:us-east-1:526980514586:function:ex6-dev-consumer"

functions:
  producer:
    handler: handler.producer
  consumer:
    handler: handler.consumer